[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
image = "0.24.7"
itertools = "0.12.0"
priority-queue = "1.3.2"
regex = "1.10.2"
